import { useRef } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import {
  Building2,
  User,
  MapPin,
  Calendar,
  IndianRupee,
  FileText,
  Download,
  Mail
} from "lucide-react";

interface TripFinancePDFProps {
  tripData: any;
  technician: any;
  serviceRequests: any[];
  pmContainers: any[];
  wageBreakdown: any;
  generatedAt: string;
  generatedBy: string;
  onClose: () => void;
}

export function TripFinancePDF({
  tripData,
  technician,
  serviceRequests,
  pmContainers,
  wageBreakdown,
  generatedAt,
  generatedBy,
  onClose
}: TripFinancePDFProps) {
  const pdfRef = useRef<HTMLDivElement>(null);

  // Helper to safely extract city name
  const getCityName = (val: any) => {
    if (!val) return null;
    if (typeof val === 'string') return val;
    if (typeof val === 'object' && val.city) return val.city;
    return null;
  };

  const destinationName = getCityName(tripData?.destinationCity) || getCityName(tripData?.city) || 'Destination';

  const handleDownloadPDF = async () => {
    if (!pdfRef.current) return;

    try {
      // Import html2pdf dynamically
      const html2pdf = (await import('html2pdf.js')).default;

      const element = pdfRef.current;
      const opt = {
        margin: 0.5,
        filename: `Trip-Finance-Report-${technician?.name || 'Technician'}-${destinationName}.pdf`,
        image: { type: 'jpeg' as const, quality: 0.98 },
        html2canvas: {
          scale: 2,
          useCORS: true,
          allowTaint: true
        },
        jsPDF: {
          unit: 'in',
          format: 'a4',
          orientation: 'portrait' as const
        }
      };

      await html2pdf().set(opt).from(element).save();
    } catch (error) {
      console.error('PDF generation failed:', error);
      alert('Failed to generate PDF. Please try again.');
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileText className="h-5 w-5 text-red-500" />
          <h3 className="text-lg font-semibold">Trip Finance Report Preview</h3>
        </div>
        <div className="flex items-center gap-2">
          <Button onClick={handleDownloadPDF} className="gap-2">
            <Download className="h-4 w-4" />
            Download PDF
          </Button>
          <Button variant="outline" onClick={onClose}>
            Close
          </Button>
        </div>
      </div>

      {/* PDF Content */}
      <div ref={pdfRef} className="bg-white p-8 max-w-4xl mx-auto shadow-lg border">
        {/* Header */}
        <div className="text-center border-b-2 border-gray-300 pb-6 mb-6">
          <h1 className="text-3xl font-bold text-gray-800 mb-2">TRIP FINANCE APPROVAL REPORT</h1>
          <h2 className="text-xl text-gray-600 mb-4">
            {technician?.name || 'Technician'} - {destinationName}
          </h2>
          <div className="flex justify-between text-sm text-gray-500">
            <span>Report ID: TRIP-{Date.now()}</span>
            <span>Generated: {new Date(generatedAt).toLocaleString()}</span>
          </div>
          <div className="text-sm text-gray-500 mt-1">
            Generated by: {generatedBy}
          </div>
        </div>

        {/* Trip Details */}
        <div className="mb-8">
          <h3 className="text-xl font-bold text-gray-800 mb-4 border-b border-gray-300 pb-2">TRIP DETAILS</h3>
          <div className="grid grid-cols-2 gap-6">
            <div>
              <h4 className="font-semibold text-gray-700 mb-3 flex items-center gap-2">
                <User className="h-4 w-4" />
                Technician Information
              </h4>
              <div className="space-y-1 text-sm">
                <div><span className="font-medium">Name:</span> {technician?.name}</div>
                <div><span className="font-medium">Employee Code:</span> {technician?.employeeCode}</div>
                <div><span className="font-medium">Grade:</span> {technician?.grade || 'N/A'}</div>
                <div><span className="font-medium">Designation:</span> {technician?.designation || 'N/A'}</div>
                <div><span className="font-medium">Base Location:</span> {technician?.baseLocation || 'N/A'}</div>
              </div>
            </div>

            <div>
              <h4 className="font-semibold text-gray-700 mb-3 flex items-center gap-2">
                <MapPin className="h-4 w-4" />
                Trip Information
              </h4>
              <div className="space-y-1 text-sm">
                <div><span className="font-medium">Destination:</span> {destinationName}</div>
                <div><span className="font-medium">Start Date:</span> {new Date(tripData?.range?.start || tripData?.startDate).toLocaleDateString()}</div>
                <div><span className="font-medium">End Date:</span> {new Date(tripData?.range?.end || tripData?.endDate).toLocaleDateString()}</div>
                <div><span className="font-medium">Total Tasks:</span> {wageBreakdown?.summary?.totalTasks || 0}</div>
                <div><span className="font-medium">Service Requests:</span> {wageBreakdown?.taskBreakdown?.serviceRequests?.count || 0}</div>
                <div><span className="font-medium">PM Tasks:</span> {wageBreakdown?.taskBreakdown?.pmTasks?.count || 0}</div>
              </div>
            </div>
          </div>
        </div>

        {/* Service Requests */}
        {serviceRequests?.length > 0 && (
          <div className="mb-8">
            <h3 className="text-xl font-bold text-gray-800 mb-4 border-b border-gray-300 pb-2">SERVICE REQUESTS</h3>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse border border-gray-300">
                <thead>
                  <tr className="bg-gray-100">
                    <th className="border border-gray-300 p-2 text-left font-semibold">Request #</th>
                    <th className="border border-gray-300 p-2 text-left font-semibold">Container</th>
                    <th className="border border-gray-300 p-2 text-left font-semibold">Issue</th>
                    <th className="border border-gray-300 p-2 text-left font-semibold">Customer</th>
                    <th className="border border-gray-300 p-2 text-left font-semibold">Priority</th>
                    <th className="border border-gray-300 p-2 text-left font-semibold">Cost</th>
                  </tr>
                </thead>
                <tbody>
                  {serviceRequests.map((sr, index) => (
                    <tr key={index} className="border-b border-gray-200">
                      <td className="border border-gray-300 p-2">{sr.requestNumber}</td>
                      <td className="border border-gray-300 p-2">{sr.containerId?.substring(0, 8)}</td>
                      <td className="border border-gray-300 p-2 max-w-xs truncate">{sr.issueDescription}</td>
                      <td className="border border-gray-300 p-2">{sr.customer?.companyName || 'N/A'}</td>
                      <td className="border border-gray-300 p-2">
                        <Badge variant={sr.priority?.toLowerCase() === 'high' ? 'destructive' : 'secondary'}>
                          {sr.priority || 'Medium'}
                        </Badge>
                      </td>
                      <td className="border border-gray-300 p-2">₹{wageBreakdown?.taskBreakdown?.serviceRequests?.rate?.toLocaleString() || '2,500'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* PM Tasks */}
        {pmContainers?.length > 0 && (
          <div className="mb-8">
            <h3 className="text-xl font-bold text-gray-800 mb-4 border-b border-gray-300 pb-2">PREVENTIVE MAINTENANCE TASKS</h3>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse border border-gray-300">
                <thead>
                  <tr className="bg-gray-100">
                    <th className="border border-gray-300 p-2 text-left font-semibold">Container</th>
                    <th className="border border-gray-300 p-2 text-left font-semibold">Customer</th>
                    <th className="border border-gray-300 p-2 text-left font-semibold">PM Status</th>
                    <th className="border border-gray-300 p-2 text-left font-semibold">Days Since PM</th>
                    <th className="border border-gray-300 p-2 text-left font-semibold">Priority</th>
                    <th className="border border-gray-300 p-2 text-left font-semibold">Cost</th>
                  </tr>
                </thead>
                <tbody>
                  {pmContainers.map((container, index) => (
                    <tr key={index} className="border-b border-gray-200">
                      <td className="border border-gray-300 p-2">{container.containerCode}</td>
                      <td className="border border-gray-300 p-2">{container.customer?.companyName || 'N/A'}</td>
                      <td className="border border-gray-300 p-2">
                        <Badge variant={
                          container.pmDetails?.pmStatus === 'OVERDUE' ? 'destructive' :
                            container.pmDetails?.pmStatus === 'NEVER' ? 'destructive' :
                              'secondary'
                        }>
                          {container.pmDetails?.pmStatus || 'UNKNOWN'}
                        </Badge>
                      </td>
                      <td className="border border-gray-300 p-2">{container.pmDetails?.daysSincePm || 'N/A'}</td>
                      <td className="border border-gray-300 p-2">
                        <Badge variant={
                          container.pmDetails?.pmStatus === 'OVERDUE' ? 'destructive' :
                            container.pmDetails?.pmStatus === 'NEVER' ? 'destructive' :
                              'secondary'
                        }>
                          {container.pmDetails?.pmStatus === 'OVERDUE' ? 'HIGH' :
                            container.pmDetails?.pmStatus === 'NEVER' ? 'CRITICAL' : 'MEDIUM'}
                        </Badge>
                      </td>
                      <td className="border border-gray-300 p-2">₹{wageBreakdown?.taskBreakdown?.pmTasks?.rate?.toLocaleString() || '1,800'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Wage Breakdown */}
        <div className="mb-8">
          <h3 className="text-xl font-bold text-gray-800 mb-4 border-b border-gray-300 pb-2">WAGE BREAKDOWN & COST ANALYSIS</h3>

          {/* Task Costs */}
          <div className="mb-6">
            <h4 className="font-semibold text-gray-700 mb-3">Task Costs</h4>
            <div className="grid grid-cols-2 gap-4">
              <Card>
                <CardContent className="p-4">
                  <div className="flex justify-between items-center">
                    <div>
                      <p className="font-medium">Service Requests</p>
                      <p className="text-sm text-gray-600">
                        {wageBreakdown?.taskBreakdown?.serviceRequests?.count || 0} × ₹{wageBreakdown?.taskBreakdown?.serviceRequests?.rate?.toLocaleString() || '2,500'}
                      </p>
                    </div>
                    <p className="text-xl font-bold text-green-600">
                      ₹{wageBreakdown?.taskBreakdown?.serviceRequests?.total?.toLocaleString() || '0'}
                    </p>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardContent className="p-4">
                  <div className="flex justify-between items-center">
                    <div>
                      <p className="font-medium">PM Tasks</p>
                      <p className="text-sm text-gray-600">
                        {wageBreakdown?.taskBreakdown?.pmTasks?.count || 0} × ₹{wageBreakdown?.taskBreakdown?.pmTasks?.rate?.toLocaleString() || '1,800'}
                      </p>
                    </div>
                    <p className="text-xl font-bold text-green-600">
                      ₹{wageBreakdown?.taskBreakdown?.pmTasks?.total?.toLocaleString() || '0'}
                    </p>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>

          {/* Allowances */}
          <div className="mb-6">
            <h4 className="font-semibold text-gray-700 mb-3">Travel Allowances</h4>
            <Card>
              <CardContent className="p-4">
                <div className="grid grid-cols-3 gap-4">
                  <div>
                    <p className="font-medium">Daily Allowance</p>
                    <p className="text-sm text-gray-600">
                      ₹{wageBreakdown?.allowances?.dailyAllowance?.rate || 0} × {wageBreakdown?.allowances?.dailyAllowance?.days || 0} days
                    </p>
                    <p className="text-lg font-bold">₹{wageBreakdown?.allowances?.dailyAllowance?.total?.toLocaleString() || '0'}</p>
                  </div>
                  <div>
                    <p className="font-medium">Hotel Allowance</p>
                    <p className="text-sm text-gray-600">
                      ₹{wageBreakdown?.allowances?.hotelAllowance?.rate || 0} × {wageBreakdown?.allowances?.hotelAllowance?.days || 0} days
                    </p>
                    <p className="text-sm font-bold">₹{wageBreakdown?.allowances?.hotelAllowance?.total?.toLocaleString() || '0'}</p>
                  </div>
                  <div>
                    <p className="font-medium">Local Travel</p>
                    <p className="text-sm text-gray-600">
                      ₹{wageBreakdown?.allowances?.localTravelAllowance?.rate || 0} × {wageBreakdown?.allowances?.localTravelAllowance?.days || 0} days
                    </p>
                    <p className="text-sm font-bold">₹{wageBreakdown?.allowances?.localTravelAllowance?.total?.toLocaleString() || '0'}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Additional Costs */}
          <div className="mb-6">
            <h4 className="font-semibold text-gray-700 mb-3">Additional Costs</h4>
            <div className="grid grid-cols-2 gap-4">
              <Card>
                <CardContent className="p-4">
                  <div className="flex justify-between items-center">
                    <div>
                      <p className="font-medium">Miscellaneous</p>
                      <p className="text-sm text-gray-600">{wageBreakdown?.additionalCosts?.miscellaneous?.percentage || 0}% of task costs</p>
                    </div>
                    <p className="text-lg font-bold">₹{wageBreakdown?.additionalCosts?.miscellaneous?.amount?.toLocaleString() || '0'}</p>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardContent className="p-4">
                  <div className="flex justify-between items-center">
                    <div>
                      <p className="font-medium">Contingency</p>
                      <p className="text-sm text-gray-600">{wageBreakdown?.additionalCosts?.contingency?.percentage || 0}% of task costs</p>
                    </div>
                    <p className="text-lg font-bold">₹{wageBreakdown?.additionalCosts?.contingency?.amount?.toLocaleString() || '0'}</p>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>

          {/* Grand Total */}
          <Card className="bg-blue-50 border-blue-200">
            <CardContent className="p-6">
              <div className="flex justify-between items-center">
                <div>
                  <h4 className="text-xl font-bold text-gray-800">TOTAL ESTIMATED COST</h4>
                  <p className="text-sm text-gray-600">
                    {wageBreakdown?.summary?.totalTasks || 0} tasks over {wageBreakdown?.summary?.estimatedDays || 0} days
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-3xl font-bold text-blue-600">
                    ₹{wageBreakdown?.summary?.totalCost?.toLocaleString('en-IN') || '0'}
                  </p>
                  <p className="text-sm text-gray-600">Including all allowances & additional costs</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Approval Section */}
        <div className="border-t-2 border-gray-300 pt-6">
          <h3 className="text-xl font-bold text-gray-800 mb-4">APPROVAL SECTION</h3>
          <div className="grid grid-cols-2 gap-8">
            <div>
              <h4 className="font-semibold text-gray-700 mb-2">Prepared By</h4>
              <div className="border-b border-gray-300 pb-2 mb-2">
                <p className="font-medium">{generatedBy}</p>
                <p className="text-sm text-gray-600">Date: {new Date(generatedAt).toLocaleDateString()}</p>
              </div>
              <p className="text-xs text-gray-500">Signature: ___________________________</p>
            </div>

            <div>
              <h4 className="font-semibold text-gray-700 mb-2">Approved By (Finance)</h4>
              <div className="border-b border-gray-300 pb-2 mb-2">
                <p className="text-gray-400">Pending Approval</p>
                <p className="text-sm text-gray-600">Date: ___________________________</p>
              </div>
              <p className="text-xs text-gray-500">Signature: ___________________________</p>
            </div>
          </div>

          <div className="mt-6">
            <h4 className="font-semibold text-gray-700 mb-2">Comments</h4>
            <div className="border border-gray-300 rounded p-3 min-h-[60px]">
              <p className="text-gray-400 text-sm">Approval comments will be added here...</p>
            </div>
          </div>

          <div className="mt-4 flex justify-center">
            <Badge variant="outline" className="px-4 py-2 text-lg">
              STATUS: PENDING FINANCE APPROVAL
            </Badge>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-8 pt-4 border-t border-gray-300 text-center text-xs text-gray-500">
          <p>This report was generated automatically by the Service Hub system on {new Date(generatedAt).toLocaleString()}</p>
          <p>Report ID: TRIP-{Date.now()} | Confidential - For Finance Department Use Only</p>
        </div>
      </div>
    </div>
  );
}
